In [2]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [7]:
import mysql.connector

host = "localhost"
port = 3307
user = "root"
password = "root"
database = "pharma_inventory"

connection = mysql.connector.connect(
    host=host,
    port=port,
    user=user,
    password=password,
    database=database
)

print("Connected Successfully!")

Connected Successfully!

In [8]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:root@localhost:3307/pharma_inventory"
)

print("Engine Created Successfully!")

Engine Created Successfully!

In [9]:
query = "SHOW TABLES;"

tables = pd.read_sql(query, engine)

tables

  Tables_in_pharma_inventory
0                  customers
1                  inventory
2                   products
3         sales_transactions
4                  suppliers

In [12]:
sales = pd.read_csv("../Data/Cleaned/sales_transactions_clean.csv")

sales.shape

(190000, 15)

In [16]:
tables = ["customers", "products", "suppliers", "inventory", "sales_transactions"]

for table in tables:
    query = f"SELECT COUNT(*) AS Total_Rows FROM {table};"
    print(table)
    print(pd.read_sql(query, engine))
    print("-" * 40)

customers
   Total_Rows
0           0
----------------------------------------
products
   Total_Rows
0           0
----------------------------------------
suppliers
   Total_Rows
0           0
----------------------------------------
inventory
   Total_Rows
0           0
----------------------------------------
sales_transactions
   Total_Rows
0           0
----------------------------------------

In [18]:
import pandas as pd

customers = pd.read_csv("../Data/Cleaned/customers_clean.csv")
products = pd.read_csv("../Data/Cleaned/products_clean.csv")
suppliers = pd.read_csv("../Data/Cleaned/suppliers_clean.csv")
inventory = pd.read_csv("../Data/Cleaned/inventory_clean.csv")
sales = pd.read_csv("../Data/Cleaned/sales_transactions_clean.csv")

In [19]:
customers.to_sql(
    "customers",
    con=engine,
    if_exists="append",
    index=False
)

print("Customers Imported Successfully!")

Customers Imported Successfully!

In [20]:
products.to_sql(
    "products",
    con=engine,
    if_exists="append",
    index=False
)

print("Products Imported Successfully!")

Products Imported Successfully!

In [21]:
suppliers.to_sql(
    "suppliers",
    con=engine,
    if_exists="append",
    index=False
)

print("Suppliers Imported Successfully!")

Suppliers Imported Successfully!

In [22]:
inventory.to_sql(
    "inventory",
    con=engine,
    if_exists="append",
    index=False
)

print("Inventory Imported Successfully!")

Inventory Imported Successfully!

In [30]:
sales.to_sql(
    "sales_transactions",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=5000,
    method="multi"
)

print("Sales Transactions Imported Successfully!")

Sales Transactions Imported Successfully!

In [31]:
tables = [
    "customers",
    "products",
    "suppliers",
    "inventory",
    "sales_transactions"
]

for table in tables:
    query = f"SELECT COUNT(*) AS Total_Rows FROM {table};"
    print(f"\n{table}")
    print(pd.read_sql(query, engine))

customers
   Total_Rows
0       25000

products
   Total_Rows
0        2500

suppliers
   Total_Rows
0         800

inventory
   Total_Rows
0       40000

sales_transactions
   Total_Rows
0      190000

In [32]:
#import libraries
import pandas as pd
from sqlalchemy import create_engine
import mysql.connector

In [34]:
query = """
SELECT
ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Total_Revenue
0   1.692594e+10

In [35]:
query = """
SELECT
ROUND(SUM(profit),2) AS Total_Profit
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Total_Profit
0  5.706100e+09

In [36]:
query = """
SELECT
COUNT(order_id) AS Total_Orders
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Total_Orders
0        190000

In [37]:
query = """
SELECT
ROUND(AVG(revenue),2) AS Average_Order_Value
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Average_Order_Value
0              89083.9

In [38]:
query = """
SELECT

ROUND(

SUM(
CASE
WHEN UPPER(returned)='YES'
THEN 1
ELSE 0
END
)

*100/

COUNT(*)

,2)

AS Return_Rate

FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Return_Rate
0         4.34

In [39]:
query = """
SELECT
SUM(quantity) AS Total_Quantity_Sold
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Total_Quantity_Sold
0            6173677.0

In [40]:
query = """
SELECT
ROUND(AVG(discount_pct),2) AS Average_Discount_Percentage
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Average_Discount_Percentage
0                        12.68

In [41]:
query = """
SELECT
COUNT(DISTINCT customer_id) AS Unique_Customers
FROM sales_transactions;
"""

pd.read_sql(query, engine)

   Unique_Customers
0             24991

In [42]:
query = """
SELECT
YEAR(order_date) AS Year,
MONTH(order_date) AS Month,
ROUND(SUM(revenue),2) AS Monthly_Revenue
FROM sales_transactions
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY YEAR(order_date), MONTH(order_date);
"""

pd.read_sql(query, engine)

    Year  Month  Monthly_Revenue
0   2020      1     1.774539e+08
1   2020      2     1.975668e+08
2   2020      3     2.256533e+08
3   2020      4     1.455987e+08
4   2020      5     1.324818e+08
..   ...    ...              ...
67  2025      8     3.599400e+08
68  2025      9     3.510514e+08
69  2025     10     2.270055e+08
70  2025     11     1.986385e+08
71  2025     12     2.013813e+08

[72 rows x 3 columns]

In [43]:
query = """
SELECT
YEAR(order_date) AS Year,
ROUND(SUM(revenue),2) AS Revenue
FROM sales_transactions
GROUP BY YEAR(order_date)
ORDER BY Year;
"""

pd.read_sql(query, engine)

   Year       Revenue
0  2020  2.800244e+09
1  2021  2.840601e+09
2  2022  2.828634e+09
3  2023  2.858250e+09
4  2024  2.777141e+09
5  2025  2.821072e+09

In [44]:
#Revenue by city
query = """
SELECT
city,
ROUND(SUM(revenue),2) AS Revenue
FROM sales_transactions
GROUP BY city
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

        city       Revenue
0     Mumbai  4.999865e+09
1      Delhi  4.647721e+09
2  Hyderabad  2.954915e+09
3       Pune  2.638741e+09
4  Ahmedabad  1.331087e+09
5       None  3.536127e+08

In [45]:
#Revenue by sales channel
query = """
SELECT
channel,
ROUND(SUM(revenue),2) AS Revenue
FROM sales_transactions
GROUP BY channel
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

           channel       Revenue
0  Retail Pharmacy  7.108371e+09
1         hospital  4.761295e+09
2      Distributor  4.724892e+09
3             Hosp  3.313836e+08

In [46]:
#Top 10 Highest revenue orders
query = """
SELECT
order_id,
customer_id,
city,
ROUND(revenue,2) AS Revenue
FROM sales_transactions
ORDER BY revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

    order_id customer_id       city     Revenue
0  ORD099130   CUS011166  Hyderabad  3105644.00
1  ORD111111   CUS014890       Pune  2976604.00
2  ORD165111   CUS015814      Delhi  2976604.00
3  ORD045380   CUS019923     Mumbai  2849832.53
4  ORD001708   CUS005712  Hyderabad  2814419.30
5  ORD013630   CUS001713      Delhi  2807796.10
6  ORD139457   CUS001650      Delhi  2773809.07
7  ORD181722   CUS002335  Ahmedabad  2768854.12
8  ORD134497   CUS022104     Mumbai  2762557.94
9  ORD096152   CUS002673     Mumbai  2750213.37

In [47]:
#Average revenue by city
query = """
SELECT
city,
ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales_transactions
GROUP BY city
ORDER BY Average_Revenue DESC;
"""

pd.read_sql(query, engine)

        city  Average_Revenue
0     Mumbai         89754.52
1  Ahmedabad         89376.68
2      Delhi         89079.45
3       Pune         89035.36
4       None         88403.18
5  Hyderabad         87972.70

In [48]:
#Total profit by city
query = """
SELECT
city,
ROUND(SUM(profit),2) AS Total_Profit
FROM sales_transactions
GROUP BY city
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, engine)

        city  Total_Profit
0     Mumbai  1.683282e+09
1      Delhi  1.559594e+09
2  Hyderabad  9.967246e+08
3       Pune  8.990961e+08
4  Ahmedabad  4.485418e+08
5       None  1.188620e+08

In [49]:
#revenue and profit by channels
query = """
SELECT
channel,
ROUND(SUM(revenue),2) AS Revenue,
ROUND(SUM(profit),2) AS Profit
FROM sales_transactions
GROUP BY channel
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

           channel       Revenue        Profit
0  Retail Pharmacy  7.108371e+09  2.386704e+09
1         hospital  4.761295e+09  1.609734e+09
2      Distributor  4.724892e+09  1.597847e+09
3             Hosp  3.313836e+08  1.118159e+08

In [ ]:
#Top 10 Revenue Generating Medicines
query = """
SELECT
p.medicine_name,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.medicine_name
ORDER BY Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

      medicine_name       Revenue
0         Metformin  1.236626e+09
1            Crocin  1.061387e+09
2      Pantoprazole  9.383478e+08
3  Azithromycin 865  9.341743e+08
4        Crocin 386  7.938568e+08
5         Augmentin  7.587130e+08
6      Azithromycin  7.305654e+08
7        Cetirizine  6.629100e+08
8    Cetirizine 792  5.133159e+08
9      Atorvastatin  5.074256e+08

In [ ]:
#Top 10 Most Sold Medicines
query = """
SELECT
p.medicine_name,
SUM(s.quantity) AS Quantity_Sold
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.medicine_name
ORDER BY Quantity_Sold DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

     medicine_name  Quantity_Sold
0        Augmentin       196192.0
1       Cetirizine       191594.0
2        Metformin       189340.0
3      Montelukast       189191.0
4     Dolo 650 661       188761.0
5    Metformin 836       188710.0
6  Paracetamol 477       188245.0
7       Crocin 386       187920.0
8    Metformin 715       187193.0
9      Paracetamol       185683.0

In [52]:
#Revenue by medicine category
query = """
SELECT
p.category,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

      category       Revenue
0   Analgesics  5.529928e+09
1  Antibiotics  3.293217e+09
2     Diabetes  2.165022e+09
3       Gastro  1.932430e+09
4  Respiratory  1.328940e+09
5  Dermatology  1.211516e+09
6    Neurology  8.084990e+08
7   Cardiology  6.563896e+08

In [53]:
#profit by medicine category
query = """
SELECT
p.category,
ROUND(SUM(s.profit),2) AS Profit
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY Profit DESC;
"""

pd.read_sql(query, engine)

      category        Profit
0   Analgesics  1.788845e+09
1  Antibiotics  1.121384e+09
2       Gastro  8.144784e+08
3     Diabetes  5.833943e+08
4  Respiratory  5.004688e+08
5  Dermatology  4.348805e+08
6    Neurology  2.393171e+08
7   Cardiology  2.233324e+08

In [54]:
#Average selling price by category
query = """
SELECT
category,
ROUND(AVG(selling_price),2) AS Average_Selling_Price
FROM products
GROUP BY category
ORDER BY Average_Selling_Price DESC;
"""

pd.read_sql(query, engine)

      category  Average_Selling_Price
0       Gastro                3256.97
1  Respiratory                3186.32
2  Antibiotics                3102.82
3   Analgesics                3066.31
4    Neurology                3034.24
5     Diabetes                3021.84
6   Cardiology                2985.58
7  Dermatology                2559.88

In [55]:
#top 10 highest profit medicine
query = """
SELECT
p.medicine_name,
ROUND(SUM(s.profit),2) AS Profit
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.medicine_name
ORDER BY Profit DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

      medicine_name        Profit
0         Metformin  5.751412e+08
1            Crocin  4.377520e+08
2      Pantoprazole  3.889315e+08
3  Azithromycin 865  3.440678e+08
4      Azithromycin  3.203734e+08
5        Crocin 386  3.168444e+08
6      Atorvastatin  2.244722e+08
7       Montelukast  2.080028e+08
8       Amoxicillin  1.337417e+08
9         Augmentin  1.212527e+08

In [56]:
#Bottom 10 medicines by revenue
query = """
SELECT
p.medicine_name,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.medicine_name
ORDER BY Revenue ASC
LIMIT 10;
"""

pd.read_sql(query, engine)

      medicine_name   Revenue
0    Cetirizine 750  12874.41
1  Pantoprazole 761  17148.81
2   Amoxicillin 112  18691.75
3       Dolo 650 79  20130.67
4      Dolo 650 360  21098.91
5  Azithromycin 774  24289.37
6    Amoxicillin 86  25115.69
7   Azithromycin 60  25402.38
8      Augmentin 92  25800.31
9   Montelukast 565  26054.98

In [57]:
#product performance summary
query = """
SELECT
p.category,
COUNT(DISTINCT p.product_id) AS Total_Products,
SUM(s.quantity) AS Total_Quantity,
ROUND(SUM(s.revenue),2) AS Revenue,
ROUND(SUM(s.profit),2) AS Profit
FROM products p
JOIN sales_transactions s
ON p.product_id = s.product_id
GROUP BY p.category
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

      category  Total_Products  Total_Quantity       Revenue        Profit
0   Analgesics             575       1864509.0  5.529928e+09  1.788845e+09
1  Antibiotics             584       1487472.0  3.293217e+09  1.121384e+09
2     Diabetes             306        855799.0  2.165022e+09  5.833943e+08
3       Gastro             245        433348.0  1.932430e+09  8.144784e+08
4  Respiratory             281        651474.0  1.328940e+09  5.004688e+08
5  Dermatology             122        307848.0  1.211516e+09  4.348805e+08
6    Neurology             133        322980.0  8.084990e+08  2.393171e+08
7   Cardiology             254        250247.0  6.563896e+08  2.233324e+08

In [58]:
#Top 10 customers by revenue
query = """
SELECT
c.customer_name,
c.customer_type,
c.city,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name, c.customer_type, c.city
ORDER BY Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  customer_name customer_type       city     Revenue
0  Global 11436      Pharmacy     Mumbai  5105163.52
1    Care 13522      Pharmacy  Ahmedabad  4841098.32
2   Metro 11165      Pharmacy     Mumbai  4574177.62
3    Life 16499      Pharmacy  Hyderabad  4059869.89
4   Global 2672      Pharmacy       Pune  4023787.21
5    Prime 6718   Distributor     Mumbai  3987808.48
6   Prime 22262      Pharmacy  Hyderabad  3895070.57
7    Apex 22793      Pharmacy  Hyderabad  3831536.69
8    Life 19922      Hospital  Hyderabad  3794502.80
9     Care 8609      Hospital  Ahmedabad  3738060.12

In [59]:
#Customer type analysis
query = """
SELECT
customer_type,
COUNT(*) AS Total_Customers
FROM customers
GROUP BY customer_type;
"""

pd.read_sql(query, engine)

  customer_type  Total_Customers
0      Pharmacy            15034
1      Hospital             6229
2   Distributor             3737

In [60]:
#Revenue by customer type
query = """
SELECT
c.customer_type,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.customer_type
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

  customer_type       Revenue
0      Pharmacy  1.014855e+10
1      Hospital  4.149955e+09
2   Distributor  2.494971e+09

In [61]:
#Revenue by hospital type
query = """
SELECT
c.hospital_type,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.hospital_type
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

      hospital_type       Revenue
0    Not Applicable  1.264352e+10
1           Private  2.291838e+09
2        Government  1.433246e+09
3  Unknown Hospital  4.248710e+08

In [62]:
#Top 10 cities by customer count
query = """
SELECT
city,
COUNT(*) AS Total_Customers
FROM customers
GROUP BY city
ORDER BY Total_Customers DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

        city  Total_Customers
0     Mumbai             7181
1      Delhi             5527
2       Pune             4508
3  Hyderabad             4306
4  Ahmedabad             2965
5    Unknown              513

In [63]:
#revenue by customer city
query = """
SELECT
c.city,
ROUND(SUM(s.revenue),2) AS Revenue
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.city
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

        city       Revenue
0     Mumbai  4.847928e+09
1      Delhi  3.669145e+09
2       Pune  2.985313e+09
3  Hyderabad  2.947796e+09
4  Ahmedabad  1.987199e+09
5    Unknown  3.560910e+08

In [64]:
#Average revenue per customer
query = """
SELECT
c.customer_name,
ROUND(AVG(s.revenue),2) AS Average_Revenue
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY Average_Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  customer_name  Average_Revenue
0    Care 14889       1023121.24
1   Prime 22195        654558.49
2     Apex 1712        641462.05
3     Care 5351        638769.74
4   Prime 17762        638439.89
5  Global 18953        628541.86
6    Life 19171        600416.07
7   Prime 14103        596370.74
8    Life 23195        550906.54
9  Global 21316        550105.76

In [65]:
#Customer purchase frequency
query = """
SELECT
c.customer_name,
COUNT(s.order_id) AS Total_Orders
FROM sales_transactions s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY Total_Orders DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  customer_name  Total_Orders
0    Prime 8391            22
1    Apex 22455            20
2    Life 17959            20
3    Care 18101            19
4  Global 21406            19
5    Care 13157            18
6    Prime 3854            18
7  Global 19822            18
8    Apex 18752            18
9    Care 17058            18

In [69]:
#Total stock summary
query = """
SELECT

SUM(stock_in) AS Total_Stock_In,
SUM(stock_out) AS Total_Stock_Out,
SUM(current_stock) AS Current_Stock

FROM inventory;
"""

pd.read_sql(query, engine)

   Total_Stock_In  Total_Stock_Out  Current_Stock
0     202670157.0      161502546.0     50084875.0

In [70]:
#Current stock by city
query = """
SELECT

city,

SUM(current_stock) AS Available_Stock

FROM inventory

GROUP BY city

ORDER BY Available_Stock DESC;
"""

pd.read_sql(query, engine)

        city  Available_Stock
0  Hyderabad       10224292.0
1       Pune       10002385.0
2  Ahmedabad        9992137.0
3     Mumbai        9951921.0
4      Delhi        9914140.0

In [71]:
#Top 10 Products with Highest Stock
query = """
SELECT

p.medicine_name,

SUM(i.current_stock) AS Current_Stock

FROM inventory i

JOIN products p

ON i.product_id = p.product_id

GROUP BY p.medicine_name

ORDER BY Current_Stock DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

      medicine_name  Current_Stock
0  Pantoprazole 376        89683.0
1      Dolo 650 242        77637.0
2  Atorvastatin 835        73904.0
3      Dolo 650 880        70841.0
4    Cetirizine 402        68911.0
5  Pantoprazole 684        66206.0
6   Montelukast 894        65716.0
7    Cetirizine 459        65463.0
8     Metformin 281        65449.0
9      Dolo 650 705        65174.0

In [72]:
#Top 10 Products with Lowest Stock
query = """
SELECT

p.medicine_name,

SUM(i.current_stock) AS Current_Stock

FROM inventory i

JOIN products p

ON i.product_id = p.product_id

GROUP BY p.medicine_name

ORDER BY Current_Stock ASC

LIMIT 10;
"""

pd.read_sql(query, engine)

      medicine_name  Current_Stock
0       Montelukast         1539.0
1  Atorvastatin 400         2013.0
2     Augmentin 294         2393.0
3  Azithromycin 432         2645.0
4  Azithromycin 623         2663.0
5     Metformin 950         2985.0
6     Metformin 399         3815.0
7  Pantoprazole 220         4005.0
8  Azithromycin 866         4012.0
9   Amoxicillin 849         4043.0

In [73]:
#Inventory movement by category
query = """
SELECT

p.category,

SUM(i.stock_in) AS Stock_In,

SUM(i.stock_out) AS Stock_Out,

SUM(i.current_stock) AS Current_Stock

FROM inventory i

JOIN products p

ON i.product_id = p.product_id

GROUP BY p.category

ORDER BY Current_Stock DESC;
"""

pd.read_sql(query, engine)

      category    Stock_In   Stock_Out  Current_Stock
0   Analgesics  46647979.0  37222081.0     11506158.0
1  Antibiotics  46642175.0  37342358.0     11365521.0
2     Diabetes  24777849.0  19834385.0      6066059.0
3  Respiratory  23364712.0  18469313.0      5912543.0
4   Cardiology  21429984.0  16945410.0      5393423.0
5       Gastro  20316683.0  16199061.0      4989317.0
6    Neurology  10238266.0   8181785.0      2516852.0
7  Dermatology   9252509.0   7308153.0      2335002.0

In [74]:
#Average stock by category
query = """
SELECT

p.category,

ROUND(AVG(i.current_stock),2) AS Average_Current_Stock

FROM inventory i

JOIN products p

ON i.product_id = p.product_id

GROUP BY p.category

ORDER BY Average_Current_Stock DESC;
"""

pd.read_sql(query, engine)

      category  Average_Current_Stock
0  Respiratory                1291.79
1  Dermatology                1275.96
2   Cardiology                1269.64
3       Gastro                1258.66
4   Analgesics                1247.55
5     Diabetes                1244.32
6  Antibiotics                1230.43
7    Neurology                1230.13

In [75]:
#Inventory health percentage
query = """
SELECT

inventory_status,

COUNT(*) AS Products,

ROUND(

COUNT(*)*100/

(SELECT COUNT(*) FROM inventory)

,2)

AS Percentage

FROM inventory

GROUP BY inventory_status;
"""

pd.read_sql(query, engine)

  inventory_status  Products  Percentage
0          Healthy     18777       46.94
1         Stockout     11943       29.86
2        Low Stock      3300        8.25
3        Overstock      5980       14.95

In [76]:
#Total Supplier
query = """
SELECT
COUNT(*) AS Total_Suppliers
FROM suppliers;
"""

pd.read_sql(query, engine)

   Total_Suppliers
0              800

In [77]:
#supplier rating distribution
query = """
SELECT
supplier_rating,
COUNT(*) AS Total_Suppliers
FROM suppliers
GROUP BY supplier_rating
ORDER BY supplier_rating DESC;
"""

pd.read_sql(query, engine)

    supplier_rating  Total_Suppliers
0               5.0               60
1               4.9               16
2               4.8               26
3               4.7               19
4               4.6               26
5               4.5               25
6               4.4               23
7               4.3               29
8               4.2               43
9               4.1               43
10              4.0               47
11              3.9               33
12              3.8               45
13              3.7               49
14              3.6               36
15              3.5               33
16              3.4               42
17              3.3               31
18              3.2               30
19              3.1               18
20              3.0               31
21              2.9               13
22              2.8               10
23              2.7               13
24              2.6               11
25              2.5                7
26              2.4               13
27              2.3                5
28              2.2                4
29              2.1                6
30              2.0                4
31              1.9                2
32              1.8                3
33              1.5                1
34              1.2                1
35              1.0                2

In [78]:
#average delivery days
query = """
SELECT
ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM suppliers;
"""

pd.read_sql(query, engine)

   Average_Delivery_Days
0                   8.79

In [79]:
#suppliers by city
query = """
SELECT
city,
COUNT(*) AS Total_Suppliers
FROM suppliers
GROUP BY city
ORDER BY Total_Suppliers DESC;
"""

pd.read_sql(query, engine)

        city  Total_Suppliers
0     Mumbai              243
1      Delhi              188
2  Hyderabad              166
3       Pune              115
4  Ahmedabad               88

In [80]:
#revenue generated by suppliers
query = """
SELECT

sp.supplier_name,

ROUND(SUM(s.revenue),2) AS Revenue

FROM sales_transactions s

JOIN suppliers sp

ON s.supplier_id = sp.supplier_id

GROUP BY sp.supplier_name

ORDER BY Revenue DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

                 supplier_name      Revenue
0  Supplier 560 Pharma Pvt Ltd  29070841.28
1  Supplier 610 Pharma Pvt Ltd  27417426.22
2  Supplier 601 Pharma Pvt Ltd  27305419.77
3   Supplier 96 Pharma Pvt Ltd  27096920.64
4  Supplier 108 Pharma Pvt Ltd  26972911.43
5  Supplier 573 Pharma Pvt Ltd  26965444.22
6  Supplier 179 Pharma Pvt Ltd  26921574.57
7  Supplier 276 Pharma Pvt Ltd  26886781.80
8  Supplier 449 Pharma Pvt Ltd  26668378.74
9  Supplier 637 Pharma Pvt Ltd  26608659.57

In [81]:
#profit generated by suppliers
query = """
SELECT

sp.supplier_name,

ROUND(SUM(s.profit),2) AS Profit

FROM sales_transactions s

JOIN suppliers sp

ON s.supplier_id = sp.supplier_id

GROUP BY sp.supplier_name

ORDER BY Profit DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

                 supplier_name       Profit
0  Supplier 108 Pharma Pvt Ltd  10161622.62
1  Supplier 601 Pharma Pvt Ltd  10133814.67
2  Supplier 610 Pharma Pvt Ltd   9887161.25
3  Supplier 573 Pharma Pvt Ltd   9726962.55
4  Supplier 311 Pharma Pvt Ltd   9644621.22
5  Supplier 179 Pharma Pvt Ltd   9621195.91
6   Supplier 92 Pharma Pvt Ltd   9583194.04
7  Supplier 231 Pharma Pvt Ltd   9494708.55
8  Supplier 560 Pharma Pvt Ltd   9412622.22
9   Supplier 96 Pharma Pvt Ltd   9404635.07

In [82]:
#Average revenue per supplier
query = """
SELECT

sp.supplier_name,

ROUND(AVG(s.revenue),2) AS Average_Revenue

FROM sales_transactions s

JOIN suppliers sp

ON s.supplier_id = sp.supplier_id

GROUP BY sp.supplier_name

ORDER BY Average_Revenue DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

                 supplier_name  Average_Revenue
0  Supplier 245 Pharma Pvt Ltd        123124.00
1  Supplier 637 Pharma Pvt Ltd        117737.43
2  Supplier 184 Pharma Pvt Ltd        117352.01
3  Supplier 710 Pharma Pvt Ltd        115447.45
4   Supplier 28 Pharma Pvt Ltd        114640.22
5  Supplier 294 Pharma Pvt Ltd        113968.20
6   Supplier 90 Pharma Pvt Ltd        113873.62
7   Supplier 65 Pharma Pvt Ltd        113242.24
8  Supplier 516 Pharma Pvt Ltd        113173.89
9  Supplier 580 Pharma Pvt Ltd        112659.20

In [83]:
#supplier performance summary
query = """
SELECT

sp.supplier_name,

sp.supplier_rating,

sp.delivery_days,

COUNT(s.order_id) AS Total_Orders,

ROUND(SUM(s.revenue),2) AS Revenue,

ROUND(SUM(s.profit),2) AS Profit

FROM suppliers sp

LEFT JOIN sales_transactions s

ON sp.supplier_id = s.supplier_id

GROUP BY
sp.supplier_id,
sp.supplier_name,
sp.supplier_rating,
sp.delivery_days

ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

,supplier_name,supplier_rating,delivery_days,Total_Orders,Revenue,Profit
0,Supplier 560 Pharma Pvt Ltd,3.7,10,273,29070841.28,9412622.22
1,Supplier 610 Pharma Pvt Ltd,2.9,14,251,27417426.22,9887161.25
2,Supplier 601 Pharma Pvt Ltd,3.8,8,275,27305419.77,10133814.67
3,Supplier 96 Pharma Pvt Ltd,2.8,14,262,27096920.64,9404635.07
4,Supplier 108 Pharma Pvt Ltd,3.7,8,261,26972911.43,10161622.62
...,...,...,...,...,...,...
795,Supplier 76 Pharma Pvt Ltd,3.5,11,220,14630783.13,4583773.88
796,Supplier 335 Pharma Pvt Ltd,4.8,3,202,14300902.58,4550476.76
797,Supplier 193 Pharma Pvt Ltd,1.8,23,209,14197326.35,4507544.03
798,Supplier 429 Pharma Pvt Ltd,3.6,9,220,13623570.95,4923823.81
799,Supplier 662 Pharma Pvt Ltd,4.6,4,205,13458569.82,4553162.89

In [84]:
#Top 10 Customers using RANK()
query = """
SELECT *

FROM (

SELECT

c.customer_name,

ROUND(SUM(s.revenue),2) AS Revenue,

RANK() OVER(
ORDER BY SUM(s.revenue) DESC
) AS Revenue_Rank

FROM sales_transactions s

JOIN customers c

ON s.customer_id = c.customer_id

GROUP BY c.customer_name

) Ranked_Customers

WHERE Revenue_Rank <=10;
"""

pd.read_sql(query, engine)

  customer_name     Revenue  Revenue_Rank
0  Global 11436  5105163.52             1
1    Care 13522  4841098.32             2
2   Metro 11165  4574177.62             3
3    Life 16499  4059869.89             4
4   Global 2672  4023787.21             5
5    Prime 6718  3987808.48             6
6   Prime 22262  3895070.57             7
7    Apex 22793  3831536.69             8
8    Life 19922  3794502.80             9
9     Care 8609  3738060.12            10

In [85]:
#Top 10 Medicines using DENSE_RANK()
query = """
SELECT *

FROM (

SELECT

p.medicine_name,

ROUND(SUM(s.revenue),2) AS Revenue,

DENSE_RANK() OVER(
ORDER BY SUM(s.revenue) DESC
) AS Medicine_Rank

FROM sales_transactions s

JOIN products p

ON s.product_id=p.product_id

GROUP BY p.medicine_name

) Ranked_Medicines

WHERE Medicine_Rank<=10;
"""

pd.read_sql(query, engine)

      medicine_name       Revenue  Medicine_Rank
0         Metformin  1.236626e+09              1
1            Crocin  1.061387e+09              2
2      Pantoprazole  9.383478e+08              3
3  Azithromycin 865  9.341743e+08              4
4        Crocin 386  7.938568e+08              5
5         Augmentin  7.587130e+08              6
6      Azithromycin  7.305654e+08              7
7        Cetirizine  6.629100e+08              8
8    Cetirizine 792  5.133159e+08              9
9      Atorvastatin  5.074256e+08             10

In [86]:
#Highest Revenue Order in Each City (ROW_NUMBER())
query = """
SELECT *

FROM (

SELECT

order_id,

city,

revenue,

ROW_NUMBER() OVER(

PARTITION BY city

ORDER BY revenue DESC

) AS Row_Num

FROM sales_transactions

) Ranked

WHERE Row_Num=1;
"""

pd.read_sql(query, engine)

    order_id       city     revenue  Row_Num
0  ORD011183       None  1946803.85        1
1  ORD181722  Ahmedabad  2768854.12        1
2  ORD165111      Delhi  2976604.00        1
3  ORD099130  Hyderabad  3105644.00        1
4  ORD045380     Mumbai  2849832.53        1
5  ORD111111       Pune  2976604.00        1

In [87]:
#Revenue above average
query = """
WITH AvgRevenue AS
(
SELECT
AVG(revenue) AS Avg_Revenue
FROM sales_transactions
)

SELECT

order_id,

customer_id,

revenue

FROM sales_transactions

WHERE revenue>

(
SELECT Avg_Revenue
FROM AvgRevenue
)

ORDER BY revenue DESC;
"""

pd.read_sql(query, engine)

        order_id customer_id     revenue
0      ORD099130   CUS011166  3105644.00
1      ORD111111   CUS014890  2976604.00
2      ORD165111   CUS015814  2976604.00
3      ORD045380   CUS019923  2849832.53
4      ORD001708   CUS005712  2814419.30
...          ...         ...         ...
54137  ORD018284   CUS009296    89097.72
54138  ORD005194   CUS016694    89095.37
54139  ORD100841   CUS008225    89094.72
54140  ORD013791   CUS002568    89090.14
54141  ORD095067   CUS003520    89086.16

[54142 rows x 3 columns]

In [88]:
#Category revenue using CTE
query = """
WITH CategoryRevenue AS
(

SELECT

p.category,

SUM(s.revenue) AS Revenue

FROM sales_transactions s

JOIN products p

ON s.product_id=p.product_id

GROUP BY p.category

)

SELECT *

FROM CategoryRevenue

ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

      category       Revenue
0   Analgesics  5.529928e+09
1  Antibiotics  3.293217e+09
2     Diabetes  2.165022e+09
3       Gastro  1.932430e+09
4  Respiratory  1.328940e+09
5  Dermatology  1.211516e+09
6    Neurology  8.084990e+08
7   Cardiology  6.563896e+08

In [89]:
#Customers spending above average
query = """
SELECT

customer_id,

ROUND(SUM(revenue),2) AS Revenue

FROM sales_transactions

GROUP BY customer_id

HAVING Revenue>

(

SELECT AVG(CustomerRevenue)

FROM

(

SELECT

SUM(revenue) AS CustomerRevenue

FROM sales_transactions

GROUP BY customer_id

) AvgTable

)

ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

     customer_id       Revenue
0      CUS999999  1.324695e+08
1      CUS011437  5.105164e+06
2      CUS013523  4.841098e+06
3      CUS011166  4.574178e+06
4      CUS016500  4.059870e+06
...          ...           ...
9846   CUS023533  6.774597e+05
9847   CUS013553  6.774005e+05
9848   CUS018531  6.773563e+05
9849   CUS022676  6.773456e+05
9850   CUS009515  6.773030e+05

[9851 rows x 2 columns]

In [90]:
#Product selling above average quantity
query = """
SELECT

product_id,

SUM(quantity) AS Quantity

FROM sales_transactions

GROUP BY product_id

HAVING Quantity>

(

SELECT AVG(ProductQty)

FROM

(

SELECT

SUM(quantity) AS ProductQty

FROM sales_transactions

GROUP BY product_id

) QtyTable

)

ORDER BY Quantity DESC;
"""

pd.read_sql(query, engine)

   product_id  Quantity
0   MED000012  196192.0
1   MED000011  191594.0
2   MED000004  189340.0
3   MED000010  189191.0
4   MED000014  188761.0
5   MED000018  188710.0
6   MED000015  188245.0
7   MED000020  187920.0
8   MED000019  187193.0
9   MED000001  185683.0
10  MED000017  185662.0
11  MED000003  185472.0
12  MED000002  184735.0
13  MED000006  184392.0
14  MED000005  183307.0
15  MED000009  181706.0
16  MED000016  181130.0
17  MED000007  181123.0
18  MED000013  180660.0
19  MED000008  180639.0

In [91]:
#Running revenue
query = """
SELECT

order_date,

ROUND(SUM(revenue),2) AS Daily_Revenue,

ROUND(

SUM(SUM(revenue))

OVER(

ORDER BY order_date

)

,2)

AS Running_Revenue

FROM sales_transactions

GROUP BY order_date

ORDER BY order_date;
"""

pd.read_sql(query, engine)

      order_date  Daily_Revenue  Running_Revenue
0     2020-01-01     6458547.67     6.458548e+06
1     2020-01-02     7120783.53     1.357933e+07
2     2020-01-03     6228881.03     1.980821e+07
3     2020-01-04     6164594.42     2.597281e+07
4     2020-01-05     6919883.40     3.289269e+07
...          ...            ...              ...
1939  2025-12-23     9436188.29     1.689576e+10
1940  2025-12-24     4672486.97     1.690043e+10
1941  2025-12-25     9576252.00     1.691001e+10
1942  2025-12-26     7733416.84     1.691774e+10
1943  2025-12-27     8201251.02     1.692594e+10

[1944 rows x 3 columns]

In [92]:
#revenue share by category
query = """
SELECT

p.category,

ROUND(SUM(s.revenue),2) AS Revenue,

ROUND(

SUM(s.revenue)*100/

(

SELECT SUM(revenue)

FROM sales_transactions

)

,2)

AS Revenue_Percentage

FROM sales_transactions s

JOIN products p

ON s.product_id=p.product_id

GROUP BY p.category

ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

      category       Revenue  Revenue_Percentage
0   Analgesics  5.529928e+09               32.67
1  Antibiotics  3.293217e+09               19.46
2     Diabetes  2.165022e+09               12.79
3       Gastro  1.932430e+09               11.42
4  Respiratory  1.328940e+09                7.85
5  Dermatology  1.211516e+09                7.16
6    Neurology  8.084990e+08                4.78
7   Cardiology  6.563896e+08                3.88

In [93]:
query = """
SELECT *
FROM vw_sales_summary;
"""

pd.read_sql(query, engine)

    Year  Month  Total_Orders  Total_Quantity       Revenue        Profit
0   2023      4          1601         53461.0  1.480647e+08  4.944906e+07
1   2024      1          2169         68742.0  1.840198e+08  6.288157e+07
2   2024     10          2508         80863.0  2.249928e+08  7.655585e+07
3   2020      1          2165         66535.0  1.774539e+08  5.934522e+07
4   2024      3          2491         81905.0  2.180396e+08  7.233896e+07
..   ...    ...           ...             ...           ...           ...
67  2024      9          4070        131912.0  3.507049e+08  1.168928e+08
68  2020     12          2188         70532.0  1.933257e+08  6.572966e+07
69  2025      2          2318         76409.0  2.128925e+08  7.172630e+07
70  2024      4          1527         49853.0  1.359409e+08  4.518964e+07
71  2020     11          2154         68714.0  1.887222e+08  6.225663e+07

[72 rows x 6 columns]

In [94]:
query = """
SELECT *
FROM vw_product_performance;
"""

pd.read_sql(query, engine)

,product_id,medicine_name,category,Quantity_Sold,Revenue,Profit
0,MED000001,Paracetamol,Antibiotics,185683.0,1.751634e+08,6.229419e+07
1,MED000002,Dolo 650,Respiratory,184735.0,8.495309e+07,2.289920e+07
2,MED000003,Crocin,Analgesics,185472.0,1.061387e+09,4.377520e+08
3,MED000004,Metformin,Gastro,189340.0,1.236626e+09,5.751412e+08
4,MED000005,Azithromycin,Analgesics,183307.0,7.305654e+08,3.203734e+08
...,...,...,...,...,...,...
2495,MED002496,Atorvastatin 976,Cardiology,1073.0,2.685188e+06,2.956177e+05
2496,MED002497,Amoxicillin 961,Cardiology,646.0,4.852439e+04,2.085540e+04
2497,MED002498,Crocin 806,Antibiotics,892.0,2.105867e+06,5.884845e+04
2498,MED002499,Metformin 489,Antibiotics,916.0,8.249832e+05,2.200691e+05
2499,MED002500,Montelukast 229,Gastro,676.0,2.792792e+06,1.055323e+06

In [95]:
query = """
SELECT *
FROM vw_inventory_summary;
"""

pd.read_sql(query, engine)

         city inventory_status    Stock_In   Stock_Out  Current_Stock
0   Ahmedabad          Healthy  17605998.0  12698986.0      4907012.0
1      Mumbai         Stockout  12411176.0  14257367.0            0.0
2      Mumbai          Healthy  17985283.0  13046846.0      4938437.0
3        Pune          Healthy  17638027.0  12711439.0      4926588.0
4   Ahmedabad         Stockout  11928612.0  13700308.0            0.0
5   Hyderabad        Low Stock   1617505.0   1553519.0        63986.0
6       Delhi          Healthy  16980828.0  12313525.0      4667303.0
7        Pune         Stockout  11979671.0  13739407.0            0.0
8   Ahmedabad        Overstock   9249332.0   4228173.0      5021159.0
9   Hyderabad         Stockout  11553246.0  13266308.0            0.0
10  Hyderabad        Overstock   9647526.0   4419046.0      5228480.0
11  Hyderabad          Healthy  17836613.0  12904787.0      4931826.0
12       Pune        Low Stock   1608178.0   1545768.0        62410.0
13  Ahmedabad        Low Stock   1518035.0   1454069.0        63966.0
14      Delhi        Low Stock   1542502.0   1476491.0        66011.0
15       Pune        Overstock   9280710.0   4267323.0      5013387.0
16     Mumbai        Overstock   9133953.0   4183525.0      4950428.0
17     Mumbai        Low Stock   1595737.0   1532681.0        63056.0
18      Delhi         Stockout  11988076.0  13814655.0            0.0
19      Delhi        Overstock   9569149.0   4388323.0      5180826.0

In [96]:
query = """
SELECT *
FROM vw_supplier_performance;
"""

pd.read_sql(query, engine)

,supplier_name,supplier_rating,Orders,Revenue,Profit
0,Supplier 1 Pharma Pvt Ltd,3.4,221,18180440.22,6111194.78
1,Supplier 10 Pharma Pvt Ltd,5.0,225,19950008.04,6692941.19
2,Supplier 100 Pharma Pvt Ltd,4.5,218,16116165.18,5686023.48
3,Supplier 101 Pharma Pvt Ltd,5.0,234,19434459.13,6109334.95
4,Supplier 102 Pharma Pvt Ltd,3.7,234,17661526.33,5753252.64
...,...,...,...,...,...
795,Supplier 95 Pharma Pvt Ltd,3.9,231,22235367.37,6942176.54
796,Supplier 96 Pharma Pvt Ltd,2.8,262,27096920.64,9404635.07
797,Supplier 97 Pharma Pvt Ltd,2.0,244,20333577.97,7246445.88
798,Supplier 98 Pharma Pvt Ltd,4.2,253,21892747.26,8360899.95
799,Supplier 99 Pharma Pvt Ltd,2.1,233,23647521.28,7703630.26

In [97]:
query = """
CALL GetMonthlyRevenue();
"""

pd.read_sql(query, engine)

    Year  Month       Revenue
0   2020      1  1.774539e+08
1   2020      2  1.975668e+08
2   2020      3  2.256533e+08
3   2020      4  1.455987e+08
4   2020      5  1.324818e+08
..   ...    ...           ...
67  2025      8  3.599400e+08
68  2025      9  3.510514e+08
69  2025     10  2.270055e+08
70  2025     11  1.986385e+08
71  2025     12  2.013813e+08

[72 rows x 3 columns]

In [100]:
from sqlalchemy import create_engine

host = "localhost"
port = 3307
user = "root"
password = "root"
database = "pharma_inventory"

engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}"
)

print("Engine Connected Successfully!")

Engine Connected Successfully!

In [101]:
pd.read_sql("SELECT 1;", engine)

   1
0  1

In [102]:
pd.read_sql("SELECT COUNT(*) AS Total FROM sales_transactions;", engine)

    Total
0  190000

In [103]:
query = """
CALL GetTopMedicines();
"""

pd.read_sql(query, engine)

      medicine_name       Revenue
0         Metformin  1.236626e+09
1            Crocin  1.061387e+09
2      Pantoprazole  9.383478e+08
3  Azithromycin 865  9.341743e+08
4        Crocin 386  7.938568e+08
5         Augmentin  7.587130e+08
6      Azithromycin  7.305654e+08
7        Cetirizine  6.629100e+08
8    Cetirizine 792  5.133159e+08
9      Atorvastatin  5.074256e+08